-- Insert 120+ comprehensive medicines
INSERT INTO medicines (name, generic_name, manufacturer, category, form, strength, pack_size, description, requires_prescription, mrp, image_url, status) VALUES
-- Pain Relief (15 medicines)
('Paracetamol 500mg', 'Paracetamol', 'Generic Pharma', 'Pain Relief', 'tablet', '500mg', '10 tablets', 'Used for pain relief and fever reduction', false, 25.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ibuprofen 400mg', 'Ibuprofen', 'PainRelief Plus', 'Pain Relief', 'tablet', '400mg', '10 tablets', 'NSAID for pain and inflammation', false, 40.00, '/placeholder.svg?height=100&width=100', 'active'),
('Aspirin 75mg', 'Aspirin', 'CardioHealth', 'Pain Relief', 'tablet', '75mg', '30 tablets', 'Blood thinner for heart health', false, 55.00, '/placeholder.svg?height=100&width=100', 'active'),
('Diclofenac 50mg', 'Diclofenac', 'PainX', 'Pain Relief', 'tablet', '50mg', '10 tablets', 'Anti-inflammatory pain relief', true, 35.00, '/placeholder.svg?height=100&width=100', 'active'),
('Naproxen 250mg', 'Naproxen', 'FlexiRelief', 'Pain Relief', 'tablet', '250mg', '10 tablets', 'Long-lasting pain relief', false, 48.00, '/placeholder.svg?height=100&width=100', 'active'),
('Aceclofenac 100mg', 'Aceclofenac', 'AccelPain', 'Pain Relief', 'tablet', '100mg', '10 tablets', 'Effective anti-inflammatory', true, 45.00, '/placeholder.svg?height=100&width=100', 'active'),
('Mefenamic Acid 250mg', 'Mefenamic Acid', 'MefaPain', 'Pain Relief', 'tablet', '250mg', '10 tablets', 'Pain and menstrual cramp relief', false, 38.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ketoprofen 100mg', 'Ketoprofen', 'KetoPain', 'Pain Relief', 'capsule', '100mg', '10 capsules', 'Anti-inflammatory pain management', false, 52.00, '/placeholder.svg?height=100&width=100', 'active'),
('Piroxicam 20mg', 'Piroxicam', 'PiroxPain', 'Pain Relief', 'capsule', '20mg', '10 capsules', 'Long duration anti-inflammatory', true, 60.00, '/placeholder.svg?height=100&width=100', 'active'),
('Etoricoxib 60mg', 'Etoricoxib', 'EtoriX', 'Pain Relief', 'tablet', '60mg', '10 tablets', 'Selective COX-2 inhibitor', true, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Meloxicam 15mg', 'Meloxicam', 'MeloRelief', 'Pain Relief', 'tablet', '15mg', '10 tablets', 'NSAID for chronic pain', true, 48.00, '/placeholder.svg?height=100&width=100', 'active'),
('Paracetamol+Tramadol', 'Paracetamol+Tramadol', 'CombiPain', 'Pain Relief', 'tablet', '500+37.5mg', '10 tablets', 'Combination pain relief', true, 78.00, '/placeholder.svg?height=100&width=100', 'active'),
('Paracetamol Syrup 250ml', 'Paracetamol', 'SyrupCare', 'Pain Relief', 'syrup', '250mg/5ml', '250ml', 'Liquid pain relief for kids', false, 45.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ibuprofen Gel', 'Ibuprofen', 'TopicalCare', 'Pain Relief', 'cream', '5%', '30g', 'Topical anti-inflammatory', false, 65.00, '/placeholder.svg?height=100&width=100', 'active'),
('Capsaicin Cream', 'Capsaicin', 'HeatRelief', 'Pain Relief', 'cream', '0.075%', '30g', 'Heat relief cream for muscles', false, 120.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Antibiotics (15 medicines)
('Amoxicillin 500mg', 'Amoxicillin', 'Beta Antibiotics', 'Antibiotic', 'capsule', '500mg', '10 capsules', 'Antibiotic for bacterial infections', true, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Azithromycin 500mg', 'Azithromycin', 'AzithroX', 'Antibiotic', 'tablet', '500mg', '3 tablets', 'Macrolide antibiotic', true, 120.00, '/placeholder.svg?height=100&width=100', 'active'),
('Cephalexin 500mg', 'Cephalexin', 'CephalX', 'Antibiotic', 'capsule', '500mg', '10 capsules', 'First generation cephalosporin', true, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Doxycycline 100mg', 'Doxycycline', 'DoxyCure', 'Antibiotic', 'capsule', '100mg', '10 capsules', 'Broad-spectrum antibiotic', true, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ciprofloxacin 500mg', 'Ciprofloxacin', 'CiproX', 'Antibiotic', 'tablet', '500mg', '10 tablets', 'Fluoroquinolone antibiotic', true, 110.00, '/placeholder.svg?height=100&width=100', 'active'),
('Norfloxacin 400mg', 'Norfloxacin', 'NorfloX', 'Antibiotic', 'tablet', '400mg', '10 tablets', 'For urinary tract infections', true, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Levofloxacin 500mg', 'Levofloxacin', 'LevoX', 'Antibiotic', 'tablet', '500mg', '10 tablets', 'Respiratory fluoroquinolone', true, 140.00, '/placeholder.svg?height=100&width=100', 'active'),
('Amoxicillin+Clavulanic', 'Amoxicillin+Clavulanic', 'AugmentX', 'Antibiotic', 'tablet', '625mg', '10 tablets', 'Beta-lactamase inhibitor combination', true, 105.00, '/placeholder.svg?height=100&width=100', 'active'),
('Cefixime 200mg', 'Cefixime', 'CefixX', 'Antibiotic', 'capsule', '200mg', '10 capsules', 'Third generation cephalosporin', true, 130.00, '/placeholder.svg?height=100&width=100', 'active'),
('Clarithromycin 250mg', 'Clarithromycin', 'ClarithX', 'Antibiotic', 'tablet', '250mg', '10 tablets', 'Macrolide antibiotic', true, 115.00, '/placeholder.svg?height=100&width=100', 'active'),
('Trimethoprim+Sulfamethoxazole', 'TMP-SMX', 'TripleSafe', 'Antibiotic', 'tablet', '160+800mg', '10 tablets', 'Combination antibiotic', true, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Metronidazole 400mg', 'Metronidazole', 'MetroX', 'Antibiotic', 'tablet', '400mg', '10 tablets', 'For anaerobic infections', true, 65.00, '/placeholder.svg?height=100&width=100', 'active'),
('Tetracycline 500mg', 'Tetracycline', 'TetraX', 'Antibiotic', 'capsule', '500mg', '10 capsules', 'Broad-spectrum antibiotic', true, 75.00, '/placeholder.svg?height=100&width=100', 'active'),
('Penicillin V 500mg', 'Penicillin V', 'PenicilX', 'Antibiotic', 'tablet', '500mg', '10 tablets', 'Oral penicillin antibiotic', true, 45.00, '/placeholder.svg?height=100&width=100', 'active'),
('Gentamicin Drops', 'Gentamicin', 'GenDrops', 'Antibiotic', 'drops', '0.3%', '10ml', 'Antibiotic eye/ear drops', false, 55.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Allergies & Cold (15 medicines)
('Cetirizine 10mg', 'Cetirizine', 'AllerCure', 'Allergy', 'tablet', '10mg', '10 tablets', 'Antihistamine for allergies', false, 45.00, '/placeholder.svg?height=100&width=100', 'active'),
('Loratadine 10mg', 'Loratadine', 'LoratallX', 'Allergy', 'tablet', '10mg', '10 tablets', 'Non-drowsy antihistamine', false, 48.00, '/placeholder.svg?height=100&width=100', 'active'),
('Fexofenadine 120mg', 'Fexofenadine', 'FexoX', 'Allergy', 'tablet', '120mg', '10 tablets', 'Non-sedating antihistamine', false, 75.00, '/placeholder.svg?height=100&width=100', 'active'),
('Pheniramine 25mg', 'Pheniramine', 'PheniX', 'Allergy', 'tablet', '25mg', '10 tablets', 'First-generation antihistamine', false, 28.00, '/placeholder.svg?height=100&width=100', 'active'),
('Montelukast 10mg', 'Montelukast', 'MonteX', 'Allergy', 'tablet', '10mg', '10 tablets', 'Leukotriene receptor antagonist', true, 145.00, '/placeholder.svg?height=100&width=100', 'active'),
('Azelastine Nasal Spray', 'Azelastine', 'AzalSpray', 'Allergy', 'drops', '0.1%', '30ml', 'Nasal antihistamine spray', false, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Fluticasone Nasal Spray', 'Fluticasone', 'FlutSpray', 'Allergy', 'spray', '50mcg', '120 doses', 'Nasal corticosteroid', false, 185.00, '/placeholder.svg?height=100&width=100', 'active'),
('Cough Syrup', 'Dextromethorphan', 'ReliefMed', 'Cold & Cough', 'syrup', '100ml', '100ml bottle', 'Relief from dry cough', false, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ambroxol Syrup', 'Ambroxol', 'AmbroCare', 'Cold & Cough', 'syrup', '30mg/5ml', '100ml', 'Expectorant for productive cough', false, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Salbutamol Inhaler', 'Salbutamol', 'BreathEasy', 'Cold & Cough', 'inhaler', '100mcg', '200 doses', 'Relief for asthma and breathing problems', true, 295.00, '/placeholder.svg?height=100&width=100', 'active'),
('Fluticasone+Salmeterol', 'Fluticasone+Salmeterol', 'DualBreath', 'Cold & Cough', 'inhaler', '50+25mcg', '120 doses', 'Combination asthma inhaler', true, 445.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ipratropium Inhaler', 'Ipratropium', 'IpraBreathe', 'Cold & Cough', 'inhaler', '20mcg', '200 doses', 'Anticholinergic bronchodilator', true, 325.00, '/placeholder.svg?height=100&width=100', 'active'),
('Guaifenesin Syrup', 'Guaifenesin', 'ExpectoCare', 'Cold & Cough', 'syrup', '100mg/5ml', '100ml', 'Expectorant for mucus clearance', false, 75.00, '/placeholder.svg?height=100&width=100', 'active'),
('Lozenge Throat', 'Benzocaine+Menthol', 'ThroatLoz', 'Cold & Cough', 'tablet', '5+3mg', '20 lozenges', 'Sore throat relief lozenges', false, 35.00, '/placeholder.svg?height=100&width=100', 'active'),
('Zinc Supplement', 'Zinc', 'ZincBoost', 'Cold & Cough', 'tablet', '15mg', '30 tablets', 'Immune support supplement', false, 85.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Digestive Health (15 medicines)
('Omeprazole 20mg', 'Omeprazole', 'DigestCare', 'Digestive', 'capsule', '20mg', '15 capsules', 'Reduces stomach acid', false, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Pantoprazole 40mg', 'Pantoprazole', 'PantoCare', 'Digestive', 'tablet', '40mg', '10 tablets', 'Proton pump inhibitor', true, 110.00, '/placeholder.svg?height=100&width=100', 'active'),
('Lansoprazole 30mg', 'Lansoprazole', 'LansoCare', 'Digestive', 'capsule', '30mg', '10 capsules', 'GERD treatment', true, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ranitidine 150mg', 'Ranitidine', 'RaniCare', 'Digestive', 'tablet', '150mg', '10 tablets', 'H2 receptor antagonist', false, 75.00, '/placeholder.svg?height=100&width=100', 'active'),
('Famotidine 20mg', 'Famotidine', 'FamoCare', 'Digestive', 'tablet', '20mg', '10 tablets', 'Acid reflux relief', false, 65.00, '/placeholder.svg?height=100&width=100', 'active'),
('Aluminium+Magnesium Hydroxide', 'Aluminium+Magnesium', 'AcidRelief', 'Digestive', 'syrup', '200+200mg/5ml', '200ml', 'Antacid suspension', false, 55.00, '/placeholder.svg?height=100&width=100', 'active'),
('Domperidone 10mg', 'Domperidone', 'DompeCare', 'Digestive', 'tablet', '10mg', '10 tablets', 'Anti-nausea medication', false, 48.00, '/placeholder.svg?height=100&width=100', 'active'),
('Metoclopramide 10mg', 'Metoclopramide', 'MetoCare', 'Digestive', 'tablet', '10mg', '10 tablets', 'Gastric motility enhancer', false, 35.00, '/placeholder.svg?height=100&width=100', 'active'),
('Loperamide 2mg', 'Loperamide', 'LopoCare', 'Digestive', 'capsule', '2mg', '10 capsules', 'Anti-diarrheal medication', false, 42.00, '/placeholder.svg?height=100&width=100', 'active'),
('Fybogel Sachets', 'Ispaghula Husk', 'FyboX', 'Digestive', 'powder', '3.5g', '20 sachets', 'Fiber supplement for constipation', false, 88.00, '/placeholder.svg?height=100&width=100', 'active'),
('Psyllium Husk', 'Psyllium', 'PsylliumX', 'Digestive', 'powder', '100%', '100g', 'Natural fiber supplement', false, 72.00, '/placeholder.svg?height=100&width=100', 'active'),
('Probiotics Capsule', 'Lactobacillus+Bifidobacterium', 'ProbioX', 'Digestive', 'capsule', 'Multi-strain', '10 capsules', 'Gut health supplement', false, 165.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ginger Supplement', 'Zingiber officinale', 'GingerX', 'Digestive', 'tablet', '500mg', '30 tablets', 'Digestive aid supplement', false, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Triphala Powder', 'Triphala', 'TriphalX', 'Digestive', 'powder', '100%', '100g', 'Ayurvedic digestive tonic', false, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Enzyme Supplement', 'Digestive Enzymes', 'EnzymeX', 'Digestive', 'tablet', 'Multi-enzyme', '30 tablets', 'Digestive enzyme complex', false, 145.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Diabetes Management (15 medicines)
('Metformin 500mg', 'Metformin', 'DiaboCure', 'Diabetes', 'tablet', '500mg', '30 tablets', 'Controls blood sugar in type 2 diabetes', true, 120.00, '/placeholder.svg?height=100&width=100', 'active'),
('Metformin ER 1000mg', 'Metformin ER', 'MetforminXR', 'Diabetes', 'tablet', '1000mg', '30 tablets', 'Extended release metformin', true, 145.00, '/placeholder.svg?height=100&width=100', 'active'),
('Glipizide 5mg', 'Glipizide', 'GlipCare', 'Diabetes', 'tablet', '5mg', '30 tablets', 'Sulfonylurea for diabetes', true, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Gliclazide 80mg', 'Gliclazide', 'GlicX', 'Diabetes', 'tablet', '80mg', '30 tablets', 'Second generation sulfonylurea', true, 105.00, '/placeholder.svg?height=100&width=100', 'active'),
('Pioglitazone 15mg', 'Pioglitazone', 'PiogliX', 'Diabetes', 'tablet', '15mg', '30 tablets', 'Thiazolidinedione for diabetes', true, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Sitagliptin 50mg', 'Sitagliptin', 'SitaglipX', 'Diabetes', 'tablet', '50mg', '30 tablets', 'DPP-4 inhibitor', true, 185.00, '/placeholder.svg?height=100&width=100', 'active'),
('Saxagliptin 5mg', 'Saxagliptin', 'SaxaX', 'Diabetes', 'tablet', '5mg', '30 tablets', 'Incretin enhancer', true, 175.00, '/placeholder.svg?height=100&width=100', 'active'),
('Teneligliptin 20mg', 'Teneligliptin', 'TeneX', 'Diabetes', 'tablet', '20mg', '30 tablets', 'DPP-4 inhibitor', true, 165.00, '/placeholder.svg?height=100&width=100', 'active'),
('Linagliptin 5mg', 'Linagliptin', 'LinaX', 'Diabetes', 'tablet', '5mg', '30 tablets', 'Insulin-independent agent', true, 195.00, '/placeholder.svg?height=100&width=100', 'active'),
('Vildagliptin 50mg', 'Vildagliptin', 'VildaX', 'Diabetes', 'tablet', '50mg', '30 tablets', 'DPP-4 inhibitor', true, 180.00, '/placeholder.svg?height=100&width=100', 'active'),
('Insulin Glargine', 'Insulin Glargine', 'InsulinGlargine', 'Diabetes', 'injection', '100 IU/ml', '3ml cartridge', 'Long-acting insulin', true, 1250.00, '/placeholder.svg?height=100&width=100', 'active'),
('Insulin NPH', 'Insulin NPH', 'InsulinNPH', 'Diabetes', 'injection', '100 IU/ml', '10ml vial', 'Intermediate-acting insulin', true, 850.00, '/placeholder.svg?height=100&width=100', 'active'),
('Insulin Regular', 'Insulin Regular', 'InsulinRegular', 'Diabetes', 'injection', '100 IU/ml', '10ml vial', 'Short-acting insulin', true, 950.00, '/placeholder.svg?height=100&width=100', 'active'),
('Insulin Lispro', 'Insulin Lispro', 'InsulinLispro', 'Diabetes', 'injection', '100 IU/ml', '3ml cartridge', 'Rapid-acting insulin', true, 1100.00, '/placeholder.svg?height=100&width=100', 'active'),
('Blood Glucose Monitor', 'Glucose Testing', 'GlucoMeter', 'Diabetes', 'other', 'Digital', '1 piece', 'Digital blood glucose monitor', false, 850.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Cardiovascular (12 medicines)
('Amlodipine 5mg', 'Amlodipine', 'AmlodiX', 'Cardiovascular', 'tablet', '5mg', '30 tablets', 'Calcium channel blocker for hypertension', true, 65.00, '/placeholder.svg?height=100&width=100', 'active'),
('Lisinopril 10mg', 'Lisinopril', 'LisiX', 'Cardiovascular', 'tablet', '10mg', '30 tablets', 'ACE inhibitor for high blood pressure', true, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Atorvastatin 20mg', 'Atorvastatin', 'AtorX', 'Cardiovascular', 'tablet', '20mg', '30 tablets', 'Statin for cholesterol management', true, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Losartan 50mg', 'Losartan', 'LosarX', 'Cardiovascular', 'tablet', '50mg', '30 tablets', 'Angiotensin II receptor antagonist', true, 75.00, '/placeholder.svg?height=100&width=100', 'active'),
('Metoprolol 50mg', 'Metoprolol', 'MetoX', 'Cardiovascular', 'tablet', '50mg', '30 tablets', 'Beta-blocker for heart health', true, 68.00, '/placeholder.svg?height=100&width=100', 'active'),
('Enalapril 5mg', 'Enalapril', 'EnalX', 'Cardiovascular', 'tablet', '5mg', '30 tablets', 'ACE inhibitor', true, 72.00, '/placeholder.svg?height=100&width=100', 'active'),
('Ramipril 5mg', 'Ramipril', 'RamiX', 'Cardiovascular', 'tablet', '5mg', '30 tablets', 'ACE inhibitor for heart failure', true, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Valsartan 80mg', 'Valsartan', 'ValsaX', 'Cardiovascular', 'tablet', '80mg', '30 tablets', 'ARB for hypertension', true, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Nifedipine 10mg', 'Nifedipine', 'NifediX', 'Cardiovascular', 'tablet', '10mg', '30 tablets', 'Calcium channel blocker', true, 55.00, '/placeholder.svg?height=100&width=100', 'active'),
('Rosuvastatin 20mg', 'Rosuvastatin', 'RosuX', 'Cardiovascular', 'tablet', '20mg', '30 tablets', 'High-potency statin', true, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Clopidogrel 75mg', 'Clopidogrel', 'ClopiX', 'Cardiovascular', 'tablet', '75mg', '30 tablets', 'Antiplatelet agent', true, 145.00, '/placeholder.svg?height=100&width=100', 'active'),
('Warfarin 5mg', 'Warfarin', 'WfarinX', 'Cardiovascular', 'tablet', '5mg', '30 tablets', 'Anticoagulant', true, 65.00, '/placeholder.svg?height=100&width=100', 'active'),

-- Vitamins & Supplements (13 medicines)
('Vitamin D3 60000 IU', 'Cholecalciferol', 'NutriVita', 'Vitamin', 'capsule', '60000 IU', '4 capsules', 'Vitamin D supplement', false, 180.00, '/placeholder.svg?height=100&width=100', 'active'),
('Vitamin B12 1000mcg', 'Cyanocobalamin', 'B12Plus', 'Vitamin', 'tablet', '1000mcg', '30 tablets', 'Vitamin B12 supplement', false, 125.00, '/placeholder.svg?height=100&width=100', 'active'),
('Vitamin C 1000mg', 'Ascorbic Acid', 'VitaminC', 'Vitamin', 'tablet', '1000mg', '30 tablets', 'Immune support vitamin', false, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('Multivitamin Daily', 'Multi-vitamin', 'MultiVita', 'Vitamin', 'tablet', 'Multi-formula', '30 tablets', 'Complete daily multivitamin', false, 145.00, '/placeholder.svg?height=100&width=100', 'active'),
('Iron Supplement 65mg', 'Ferrous Sulfate', 'IronCare', 'Vitamin', 'tablet', '65mg', '30 tablets', 'Iron for anemia', false, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Calcium+Vitamin D', 'Calcium Carbonate+D3', 'CalciVita', 'Vitamin', 'tablet', '500+400 IU', '30 tablets', 'Bone health supplement', false, 110.00, '/placeholder.svg?height=100&width=100', 'active'),
('Omega-3 Capsule', 'Fish Oil', 'OmegaX', 'Vitamin', 'capsule', '1000mg', '30 capsules', 'Heart health supplement', false, 165.00, '/placeholder.svg?height=100&width=100', 'active'),
('Zinc Supplement 15mg', 'Zinc', 'ZincPlus', 'Vitamin', 'tablet', '15mg', '30 tablets', 'Immune system support', false, 85.00, '/placeholder.svg?height=100&width=100', 'active'),
('Folic Acid 5mg', 'Folic Acid', 'FoliciX', 'Vitamin', 'tablet', '5mg', '30 tablets', 'For pregnant women', false, 65.00, '/placeholder.svg?height=100&width=100', 'active'),
('Magnesium 400mg', 'Magnesium Oxide', 'MagX', 'Vitamin', 'tablet', '400mg', '30 tablets', 'Mineral supplement', false, 95.00, '/placeholder.svg?height=100&width=100', 'active'),
('CoQ10 100mg', 'Coenzyme Q10', 'CoQX', 'Vitamin', 'capsule', '100mg', '30 capsules', 'Heart and energy supplement', false, 225.00, '/placeholder.svg?height=100&width=100', 'active'),
('Biotin 10000mcg', 'Biotin', 'BiotinX', 'Vitamin', 'tablet', '10000mcg', '30 tablets', 'Hair and skin health', false, 135.00, '/placeholder.svg?height=100&width=100', 'active'),
('Lutein+Zeaxanthin', 'Lutein+Zeaxanthin', 'EyeVita', 'Vitamin', 'capsule', '20+4mg', '30 capsules', 'Eye health supplement', false, 185.00, '/placeholder.svg?height=100&width=100', 'active');

-- Verify insertion
SELECT COUNT(*) as total_medicines FROM medicines;
